Repository Monkey-Market/quipus, pull requests merged in 2024-11, with the labels that each got.

#47 feat: integrate polars into quipus
  poetry.lock
  pyproject.toml
  quipus/data_sources/csv_data_source.py
  quipus/data_sources/dataframe_data_source.py
  quipus/data_sources/xlsx_data_source.py
  quipus/models/certificate_factory.py
  quipus/services/template_manager.py
  tests/test_certificate_factory.py
  tests/test_csv_source.py
  tests/test_dataframe_source.py
  tests/test_xlsx_source.py
Labels: enhancement

#48 ft/data_source_bases
  .pylintrc
  poetry.lock
  pyproject.toml
  quipus/__init__.py
  quipus/data_sources/__init__.py
  quipus/data_sources/csv_source.py
  quipus/data_sources/data_source.py
  quipus/data_sources/database_source.py
  quipus/data_sources/dataframe_data_source.py
  quipus/data_sources/file_source.py
  quipus/data_sources/mongo_source.py
  quipus/data_sources/mysql_source.py
  quipus/data_sources/parquet_source.py
  quipus/data_sources/postgre_source.py
  quipus/data_sources/postgresql_data_source.py
  quipus/data_sources/xlsx_data_source.py
  quipus/data_sources/xlsx_source.py
  quipus/services/__init__.py
  quipus/utils/__init__.py
  quipus/utils/connectable.py
  quipus/utils/dbconfig.py
  quipus/utils/types.py
  tests/test_dataframe_source.py
  tests/test_postgresql_source.py
  tests/test_xlsx_source.py
Labels: enhancement, refactor

#50 [FT] Add ReplacementsDict and ValidReplacementValue types for smtp replacements
  quipus/__init__.py
  quipus/services/smtp_delivery.py
  quipus/utils/__init__.py
  quipus/utils/types.py
Labels: enhancement, fix
